detectors:
  IrresponsibleModule:
        enabled: false
directories:
  "app/controllers|**/app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers|**/app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers|**/app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models|**/app/models":
    InstanceVariableAssumption:
      enabled: false
    Attribute:
      enabled: false

exclude_paths:
  - db/migrate
