###########################################################
#################### Rubocop Rspec ########################
###########################################################

# You can find all configuration options for rubocop-rspec here: https://docs.rubocop.org/rubocop-rspec/cops.html

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/VariableName:
  EnforcedStyle: snake_case
